const socket=io();let room=null,name="Player",gameTimer=null,score=0;
const $=s=>document.querySelector(s);const games={doodle:["DOODLE GUESS","2–7 PLAYERS"],ultimate:["ULTIMATE TIC-TAC-TOE","2 PLAYERS"],truth:["TRUTH OR DARE","2–7 PLAYERS"],would:["WOULD YOU RATHER","2–7 PLAYERS"],emoji:["EMOJI DECODE","2–7 PLAYERS"],quiz:["QUICK QUIZ","2–7 PLAYERS"],reaction:["REACTION RUSH","2–7 PLAYERS"],word:["WORD CHAIN","2–7 PLAYERS"]};
function toast(t){$("#toast").textContent=t;$("#toast").style.display="block";setTimeout(()=>$("#toast").style.display="none",1800)}
function toggleJoin(){$("#join").classList.toggle("hidden")}
function createRoom(){name=$("#playerName").value.trim()||"Player";socket.emit("room:create",{name})}
function joinRoom(){name=$("#playerName").value.trim()||"Player";socket.emit("room:join",{code:$("#roomInput").value.trim(),name})}
socket.on("room:state",r=>{room=r;$("#code").textContent=Object.keys(r).length?location.hash=r.code||$("#code").textContent:r.code||"ROOM";$("#code").textContent=$("#roomInput").value.trim().toUpperCase()||$("#code").textContent;renderPlayers();showRoom()});
socket.on("room:error",toast);
function renderPlayers(){if(!room)return;$("#players").innerHTML=room.players.map(p=>`<div class="player"><span class="av">${p.avatar}</span><b>${p.name}</b>${p.id===room.host?" <small>HOST</small>":""}</div>`).join("")}
function hideAll(){$("#room").classList.add("hidden");$("#play").classList.add("hidden")}
function goHome(){hideAll();$("#games").scrollIntoView()}
function showRoom(){hideAll();$("#room").classList.remove("hidden");window.scrollTo({top:0,behavior:"smooth"})}
function startGame(g){if(!room){toast("Create or join a room first ✨");return}socket.emit("game:start",{game:g});renderGame(g)}
socket.on("game:started",renderGame);
function renderGame(g){hideAll();$("#play").classList.remove("hidden");$("#gameName").textContent=games[g][0];$("#gameMode").textContent=games[g][1];$("#liveScore").textContent="🏆 "+score;let html="";if(g==="doodle")html=doodle();if(g==="ultimate")html=ultimate();if(g==="truth")html=truth();if(g==="would")html=would();if(g==="emoji")html=emoji();if(g==="quiz")html=quiz();if(g==="reaction")html=reaction();if(g==="word")html=word();$("#gameArea").innerHTML=html;if(g==="doodle")initDoodle();if(g==="reaction")initReaction();if(g==="word")initWord()}
function addScore(n){score+=n;$("#liveScore").textContent="🏆 "+score}
const words=["CAT","DOG","PIZZA","GUITAR","ELEPHANT","ROCKET","CAKE","SUNGLASSES","BICYCLE","TIGER","ICE CREAM","CASTLE"];
function doodle(){return `<div class="gameBox"><div class="round"><span>ROUND 1 / 5</span><span class="timer" id="tm">60</span><span>✏️ YOU ARE DRAWING</span></div><div class="doodle"><div class="canvasBox"><canvas id="cv" width="760" height="430"></canvas><div class="word">Your word: <b id="word">${words[Math.floor(Math.random()*words.length)]}</b></div></div><div class="chat"><b>💬 LIVE GUESSES</b><div class="chatLog" id="log"><div class="chatLine">Game started! Start guessing.</div></div><div class="chatInput"><input id="guess" placeholder="Guess the word…" onkeydown="if(event.key==='Enter')guess()"><button onclick="guess()">Send</button></div></div></div><div class="toolbar"><button onclick="clearDraw()">Clear</button><button onclick="eraser()">🧽 Eraser</button><input id="brush" type="range" min="2" max="24" value="6"><button class="neon small" onclick="nextDoodle()">NEXT ROUND →</button></div></div>`}
let ctx,drawing=false,erase=false;
function initDoodle(){let c=$("#cv");ctx=c.getContext("2d");ctx.fillStyle="white";ctx.fillRect(0,0,c.width,c.height);c.onpointerdown=e=>{drawing=true;stroke(e)};c.onpointerup=()=>drawing=false;c.onpointerleave=()=>drawing=false;c.onpointermove=e=>drawing&&stroke(e);let n=60;clearInterval(gameTimer);gameTimer=setInterval(()=>{$("#tm").textContent=--n;if(n<=0)clearInterval(gameTimer)},1000)}
function stroke(e){let c=$("#cv"),r=c.getBoundingClientRect(),x=(e.clientX-r.left)*c.width/r.width,y=(e.clientY-r.top)*c.height/r.height;ctx.lineWidth=+$("#brush").value;ctx.lineCap="round";ctx.strokeStyle=erase?"white":"#111";ctx.lineTo(x,y);ctx.stroke();ctx.beginPath();ctx.moveTo(x,y);socket.emit("draw:stroke",{x,y,w:ctx.lineWidth,color:ctx.strokeStyle})}
socket.on("draw:stroke",d=>{if(!ctx)return;ctx.lineWidth=d.w;ctx.strokeStyle=d.color;ctx.lineTo(d.x,d.y);ctx.stroke();ctx.beginPath();ctx.moveTo(d.x,d.y)});
function clearDraw(){ctx.fillStyle="white";ctx.fillRect(0,0,$("#cv").width,$("#cv").height);ctx.beginPath();socket.emit("draw:clear")}
socket.on("draw:clear",()=>{if(ctx){ctx.fillStyle="white";ctx.fillRect(0,0,$("#cv").width,$("#cv").height);ctx.beginPath()}})
function eraser(){erase=!erase;toast(erase?"Eraser on":"Pen on")}
function guess(){let i=$("#guess"),v=i.value.trim();if(!v)return;let correct=v.toUpperCase()===$("#word").textContent;if(correct){addScore(100);$("#log").innerHTML+=`<div class="chatLine">🎉 <b>Correct!</b> +100</div>`}else $("#log").innerHTML+=`<div class="chatLine">You: ${v}</div>`;i.value=""}
function nextDoodle(){toast("Next round started!");initDoodle();$("#word").textContent=words[Math.floor(Math.random()*words.length)]}

let board,turn;
function ultimate(){return `<div class="gameBox"><div class="round"><span>ULTIMATE TIC-TAC-TOE</span><span id="ut">X'S TURN</span></div><div class="ttt" id="ttt">${Array(9).fill(0).map((_,i)=>`<button onclick="move(${i})"></button>`).join("")}</div><div style="text-align:center"><button class="ghost" onclick="resetTTT()">RESET BOARD</button></div></div>`}
function resetTTT(){board=Array(9).fill("");turn="X";paintTTT()}function paintTTT(){if(!$("#ttt"))return;$("#ttt").innerHTML=board.map((x,i)=>`<button onclick="move(${i})">${x}</button>`).join("");$("#ut").textContent=turn+"'S TURN"}function move(i){if(board[i])return;board[i]=turn;if(win(board)){toast(turn+" wins! 🏆");addScore(250);return}turn=turn==="X"?"O":"X";paintTTT();socket.emit("ttt:move",{i,turn})}function win(a){return [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(q=>a[q[0]]&&a[q[0]]===a[q[1]]&&a[q[1]]===a[q[2]])}board=Array(9).fill("");turn="X";socket.on("ttt:move",d=>{if(!board[d.i]){board[d.i]=d.turn==="X"?"O":"X";turn=d.turn;paintTTT()}});

const truths=[["TRUTH","What is your most useless talent?"],["DARE","Do your best celebrity impression for 20 seconds."],["TRUTH","What is the funniest thing you've done to impress someone?"],["DARE","Talk like a robot until your next turn."],["TRUTH","Who would survive longest in a zombie apocalypse?"],["DARE","Make your weirdest face for 10 seconds."]];
function truth(){return `<div class="fun"><div class="emoji">🎭</div><div class="eyebrow" id="ttype">TRUTH</div><h3 id="tp">Click below to reveal your challenge.</h3><button class="neon" onclick="newTruth()">NEW CARD</button></div>`}function newTruth(){let x=truths[Math.floor(Math.random()*truths.length)];$("#ttype").textContent=x[0];$("#tp").textContent=x[1]}

const wr=[["Have unlimited money","Have unlimited free time"],["Fly","Be invisible"],["Never use social media","Never watch movies"],["Always be early","Always be late"]];
function would(){return `<div class="fun"><div class="emoji">🤔</div><h3>Would you rather…</h3><div class="choices"><button id="wa"></button><button id="wb"></button></div><p id="wv"></p><button class="ghost" onclick="newWould()">NEW CHOICE</button></div>`}function newWould(){let x=wr[Math.floor(Math.random()*wr.length)];$("#wa").textContent=x[0];$("#wb").textContent=x[1];$("#wv").textContent=""}function vote(x){$("#wv").textContent="You picked "+x+" 🎉"}

const em=[["🐱👑","cat king"],["🌧️☀️","weather"],["🍕❤️","love pizza"],["🚀🌙","moon rocket"],["🐝🍯","honey bee"]];
function emoji(){let x=em[Math.floor(Math.random()*em.length)];return `<div class="fun"><div class="emoji">${x[0]}</div><h3>What does this mean?</h3><input class="answer" id="ea" placeholder="Type your answer"><button class="neon" onclick="checkE('${x[1]}')">CHECK</button><p id="er"></p></div>`}function checkE(a){let v=$("#ea").value.trim().toLowerCase();$("#er").textContent=v===a?"🎉 Correct! +100":"❌ Try again!";if(v===a)addScore(100)}

const qs=[["Which planet is called the Red Planet?",["Mars","Venus","Jupiter","Mercury"],0],["How many sides does a hexagon have?",["5","6","7","8"],1],["What do bees make?",["Milk","Honey","Bread","Juice"],1],["Largest ocean?",["Atlantic","Indian","Pacific","Arctic"],2]];
function quiz(){let q=qs[Math.floor(Math.random()*qs.length)];return `<div class="fun"><div class="eyebrow">BRAIN RUSH</div><h3>${q[0]}</h3><div class="quizChoices">${q[1].map((x,i)=>`<button onclick="qa(${i},${q[2]})">${x}</button>`).join("")}</div><p id="qr"></p><button class="ghost" onclick="renderGame('quiz')">NEXT QUESTION</button></div>`}function qa(i,c){$("#qr").textContent=i===c?"🎉 Correct! +100":"❌ Wrong!";if(i===c)addScore(100)}

function reaction(){return `<div class="gameBox"><div class="round"><span>REACTION RUSH</span><span>Wait for GREEN</span></div><div id="react" class="reaction">WAIT…</div></div>`}function initReaction(){let r=$("#react"),delay=1200+Math.random()*3500;r.onclick=()=>{if(!r.classList.contains("go")){toast("Too early! 😈")}else{let t=performance.now()-r.dataset.start;toast(Math.round(t)+" ms! ⚡");addScore(Math.max(10,300-Math.round(t/5)));r.className="reaction";r.textContent="WAIT…";initReaction()}};setTimeout(()=>{r.className="reaction go";r.textContent="CLICK!";r.dataset.start=performance.now()},delay)}

function word(){return `<div class="fun"><div class="emoji">🔤</div><h3>Word Chain</h3><p>Type a word beginning with the last letter.</p><div class="answer" id="chain">START</div><input class="answer" id="wi" placeholder="Your word"><button class="neon" onclick="chain()">SEND WORD</button><p id="wr"></p></div>`}function chain(){let i=$("#wi"),v=i.value.trim();if(!v)return;let last=$("#chain").textContent.trim().slice(-1).toLowerCase();if(v[0].toLowerCase()!==last){$("#wr").textContent="❌ Start with "+last.toUpperCase()}else{$("#chain").textContent=v.toUpperCase();$("#wr").textContent="🔥 Chain continues!";addScore(25)}i.value=""}
function copyCode(){navigator.clipboard?.writeText($("#code").textContent);toast("Room code copied!")}
function openHome(){hideAll();window.scrollTo(0,0)}