const socket = io({ transports:['websocket','polling'] });
let room=null, myId=null, currentGame=null, gameTimer=null, ctx=null, drawing=false, erase=false;
const $=s=>document.querySelector(s);
const games={doodle:['DOODLE GUESS','2–7 PLAYERS'],ultimate:['ULTIMATE TIC-TAC-TOE','2 PLAYERS'],truth:['TRUTH OR DARE','2–7 PLAYERS'],would:['WOULD YOU RATHER','2–7 PLAYERS'],emoji:['EMOJI DECODE','2–7 PLAYERS'],quiz:['QUICK QUIZ','2–7 PLAYERS'],reaction:['REACTION RUSH','2–7 PLAYERS'],word:['WORD CHAIN','2–7 PLAYERS']};
const words=['CAT','DOG','PIZZA','GUITAR','ELEPHANT','ROCKET','CAKE','SUNGLASSES','BICYCLE','TIGER','ICE CREAM','CASTLE'];
function toast(t){const el=$('#toast');if(!el)return;el.textContent=t;el.style.display='block';clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>el.style.display='none',2200)}
function toggleJoin(){$('#join').classList.toggle('hidden');$('#playerName')?.focus()}
function createRoom(){const n=$('#playerName').value.trim()||'Player';socket.emit('room:create',{name:n})}
function joinRoom(){const n=$('#playerName').value.trim()||'Player',c=$('#roomInput').value.trim();if(!c)return toast('Enter the room code first.');socket.emit('room:join',{code:c,name:n})}
function hideAll(){$('#room').classList.add('hidden');$('#play').classList.add('hidden')}
function showRoom(){hideAll();$('#room').classList.remove('hidden');window.scrollTo({top:0,behavior:'smooth'})}
function goHome(){socket.emit('room:leave');room=null;hideAll();window.scrollTo({top:0,behavior:'smooth'})}
function renderPlayers(){if(!room)return;$('#players').innerHTML=room.players.map(p=>`<div class="player"><span class="av">${p.avatar}</span><b>${escapeHtml(p.name)}</b>${p.id===room.host?' <small>HOST</small>':''}<span style="margin-left:auto">🏆 ${p.score||0}</span></div>`).join('')}
function escapeHtml(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function startGame(g){if(!room)return toast('Create or join a room first ✨');socket.emit('game:start',{game:g})}
function copyCode(){navigator.clipboard?.writeText($('#code').textContent).then(()=>toast('Room code copied!')).catch(()=>toast('Room code: '+$('#code').textContent))}
function addScore(n){socket.emit('score:add',n)}

socket.on('connect',()=>{myId=socket.id;toast('Connected to PlayRoom ⚡')});
socket.on('connect_error',()=>toast('Could not connect to the game server. Refresh once.'));
socket.on('room:created',({code})=>{$('#code').textContent=code;toast('Room created! Share this code 🎉')});
socket.on('room:state',r=>{room=r;$('#code').textContent=r.code;renderPlayers();showRoom()});
socket.on('room:error',toast);
socket.on('scores:state',scores=>{if(!room)return;const map=new Map(scores.map(x=>[x.id,x.score]));room.players.forEach(p=>p.score=map.get(p.id)??p.score);renderPlayers();const me=scores.find(x=>x.id===myId);if(me)$('#liveScore').textContent='🏆 '+me.score});
socket.on('game:started',g=>renderGame(g));
socket.on('game:ended',msg=>{toast(msg||'Game ended');currentGame=null;showRoom()});

function renderGame(g){currentGame=g;hideAll();$('#play').classList.remove('hidden');$('#gameName').textContent=games[g][0];$('#gameMode').textContent=games[g][1];$('#liveScore').textContent='🏆 '+(room?.players.find(p=>p.id===myId)?.score||0);let html='';if(g==='doodle')html=doodle();if(g==='ultimate')html=ultimate();if(g==='truth')html=truth();if(g==='would')html=would();if(g==='emoji')html=emoji();if(g==='quiz')html=quiz();if(g==='reaction')html=reaction();if(g==='word')html=word();$('#gameArea').innerHTML=html;if(g==='doodle')initDoodle();if(g==='reaction')initReaction();if(g==='would')newWould()}

function doodle(){return `<div class="gameBox"><div class="round"><span id="dRound">ROUND 1 / 5</span><span class="timer" id="tm">60</span><span id="role">WAITING…</span></div><div class="doodle"><div class="canvasBox"><canvas id="cv" width="760" height="430"></canvas><div class="word" id="wordBox">Your word: <b id="word">Waiting…</b></div></div><div class="chat"><b>💬 LIVE GUESSES</b><div class="chatLog" id="log"><div class="chatLine">Waiting for the drawer…</div></div><div class="chatInput"><input id="guess" placeholder="Guess the word…" onkeydown="if(event.key==='Enter')guess()"><button onclick="guess()">Send</button></div></div></div><div class="toolbar"><button id="clearBtn" onclick="clearDraw()">Clear</button><button id="eraserBtn" onclick="eraser()">🧽 Eraser</button><input id="brush" type="range" min="2" max="24" value="6"><button class="neon small" onclick="showRoom()">END GAME</button></div></div>`}
function initDoodle(){ctx=null;drawing=false;erase=false;const c=$('#cv');if(!c)return;ctx=c.getContext('2d');ctx.fillStyle='white';ctx.fillRect(0,0,c.width,c.height);ctx.beginPath();c.onpointerdown=e=>{if($('#role').dataset.drawer!=='yes')return;drawing=true;stroke(e)};c.onpointerup=()=>{drawing=false;ctx?.beginPath()};c.onpointerleave=()=>{drawing=false;ctx?.beginPath()};c.onpointermove=e=>drawing&&stroke(e)}
function stroke(e){if(!ctx)return;const c=$('#cv'),r=c.getBoundingClientRect(),x=(e.clientX-r.left)*c.width/r.width,y=(e.clientY-r.top)*c.height/r.height;ctx.lineWidth=+$('#brush').value;ctx.lineCap='round';ctx.strokeStyle=erase?'white':'#111';ctx.lineTo(x,y);ctx.stroke();ctx.beginPath();ctx.moveTo(x,y);socket.emit('draw:stroke',{x,y,w:ctx.lineWidth,color:ctx.strokeStyle})}
function clearDraw(){if($('#role').dataset.drawer!=='yes')return;ctx?.clearRect(0,0,$('#cv').width,$('#cv').height);if(ctx){ctx.fillStyle='white';ctx.fillRect(0,0,$('#cv').width,$('#cv').height);ctx.beginPath()}socket.emit('draw:clear')}
function eraser(){if($('#role').dataset.drawer!=='yes')return;erase=!erase;toast(erase?'Eraser on':'Pen on')}
function guess(){const i=$('#guess'),v=i.value.trim();if(!v)return;socket.emit('doodle:guess',{guess:v});i.value=''}
socket.on('doodle:state',d=>{if(currentGame!=='doodle')return;$('#dRound').textContent=`ROUND ${d.round} / ${d.totalRounds}`;$('#tm').textContent=d.timeLeft;const role=$('#role');role.dataset.drawer=d.drawerId===myId?'yes':'no';role.textContent=d.drawerId===myId?'✏️ YOU ARE DRAWING':`🎯 ${escapeHtml(d.drawerName)} IS DRAWING`;$('#word').textContent=d.word||'Guess it!';$('#wordBox').style.display=d.word?'block':'block';$('#guess').disabled=d.drawerId===myId;$('#clearBtn').disabled=d.drawerId!==myId;$('#eraserBtn').disabled=d.drawerId!==myId;$('#brush').disabled=d.drawerId!==myId;if(d.drawerId===myId)toast('Your turn to draw! ✏️')});
socket.on('doodle:tick',n=>{if($('#tm'))$('#tm').textContent=n});
socket.on('doodle:guess',d=>{$('#log')&&(($('#log').innerHTML+=`<div class="chatLine">${escapeHtml(d.name)}: ${escapeHtml(d.guess)}</div>`),$('#log').scrollTop=$('#log').scrollHeight)});
socket.on('doodle:correct',d=>{$('#log')&&($('#log').innerHTML+=`<div class="chatLine">🎉 <b>${escapeHtml(d.name)} got it! Word: ${escapeHtml(d.word)}</b></div>`);toast(`${d.name} guessed it! +100`)});
socket.on('doodle:message',m=>{$('#log')&&($('#log').innerHTML+=`<div class="chatLine">${escapeHtml(m)}</div>`)})
socket.on('doodle:finished',()=>{toast('Doodle finished! 🎉');showRoom()});
socket.on('draw:stroke',d=>{if(!ctx)return;ctx.lineWidth=d.w;ctx.lineCap='round';ctx.strokeStyle=d.color;ctx.lineTo(d.x,d.y);ctx.stroke();ctx.beginPath();ctx.moveTo(d.x,d.y)});
socket.on('draw:clear',()=>{if(ctx){ctx.fillStyle='white';ctx.fillRect(0,0,$('#cv').width,$('#cv').height);ctx.beginPath()}});

function ultimate(){return `<div class="gameBox"><div class="round"><span>ULTIMATE TIC-TAC-TOE</span><span id="ut">X'S TURN</span></div><div class="ttt" id="ttt">${Array(9).fill('').map((_,i)=>`<button onclick="move(${i})"></button>`).join('')}</div><div style="text-align:center"><p id="tttInfo">Waiting for game…</p><button class="ghost" onclick="resetTTT()">RESET BOARD</button></div></div>`}
function move(i){socket.emit('ttt:move',{index:i})}
function resetTTT(){socket.emit('ttt:reset')}
socket.on('ttt:state',t=>{if(currentGame!=='ultimate')return;paintTTT(t);if(t.winner){toast(t.winner==='DRAW'?'Draw! 🤝':`${t.winner} wins! 🏆`)}});
function paintTTT(t){const el=$('#ttt');if(!el)return;el.innerHTML=t.board.map((x,i)=>`<button onclick="move(${i})" ${x||t.winner?'disabled':''}>${x}</button>`).join('');const me=t.players?.indexOf(myId);const symbol=me===0?'X':me===1?'O':'-';$('#ut').textContent=t.winner?(t.winner==='DRAW'?'DRAW GAME':`${t.winner} WINS!`):(t.turn===symbol?'YOUR TURN ('+symbol+')':`${t.turn}'S TURN`);$('#tttInfo').textContent=`You are ${symbol}. Only the correct player's turn can move.`}

const truths=[['TRUTH','What is your most useless talent?'],['DARE','Do your best celebrity impression for 20 seconds.'],['TRUTH','What is the funniest thing you have done to impress someone?'],['DARE','Talk like a robot until your next turn.'],['TRUTH','Who would survive longest in a zombie apocalypse?'],['DARE','Make your weirdest face for 10 seconds.']];
function truth(){return `<div class="fun"><div class="emoji">🎭</div><div class="eyebrow" id="ttype">TRUTH</div><h3 id="tp">Click below to reveal your challenge.</h3><button class="neon" onclick="newTruth()">NEW CARD</button></div>`}function newTruth(){const x=truths[Math.floor(Math.random()*truths.length)];$('#ttype').textContent=x[0];$('#tp').textContent=x[1]}
const wr=[['Have unlimited money','Have unlimited free time'],['Fly','Be invisible'],['Never use social media','Never watch movies'],['Always be early','Always be late']];
function would(){return `<div class="fun"><div class="emoji">🤔</div><h3>Would you rather…</h3><div class="choices"><button id="wa" onclick="vote($('#wa').textContent)"></button><button id="wb" onclick="vote($('#wb').textContent)"></button></div><p id="wv"></p><button class="ghost" onclick="newWould()">NEW CHOICE</button></div>`}function newWould(){const x=wr[Math.floor(Math.random()*wr.length)];$('#wa').textContent=x[0];$('#wb').textContent=x[1];$('#wv').textContent=''}function vote(x){$('#wv').textContent='You picked '+x+' 🎉'}
const em=[['🐱👑','cat king'],['🌧️☀️','weather'],['🍕❤️','love pizza'],['🚀🌙','moon rocket'],['🐝🍯','honey bee']];
function emoji(){const x=em[Math.floor(Math.random()*em.length)];return `<div class="fun"><div class="emoji">${x[0]}</div><h3>What does this mean?</h3><input class="answer" id="ea" placeholder="Type your answer"><button class="neon" onclick="checkE('${x[1]}')">CHECK</button><p id="er"></p></div>`}function checkE(a){const v=$('#ea').value.trim().toLowerCase();$('#er').textContent=v===a?'🎉 Correct! +100':'❌ Try again!';if(v===a)addScore(100)}
const qs=[['Which planet is called the Red Planet?',['Mars','Venus','Jupiter','Mercury'],0],['How many sides does a hexagon have?',['5','6','7','8'],1],['What do bees make?',['Milk','Honey','Bread','Juice'],1],['Largest ocean?',['Atlantic','Indian','Pacific','Arctic'],2]];
function quiz(){const q=qs[Math.floor(Math.random()*qs.length)];return `<div class="fun"><div class="eyebrow">BRAIN RUSH</div><h3>${q[0]}</h3><div class="quizChoices">${q[1].map((x,i)=>`<button onclick="qa(${i},${q[2]})">${x}</button>`).join('')}</div><p id="qr"></p><button class="ghost" onclick="renderGame('quiz')">NEXT QUESTION</button></div>`}function qa(i,c){$('#qr').textContent=i===c?'🎉 Correct! +100':'❌ Wrong!';if(i===c)addScore(100)}
function reaction(){return `<div class="gameBox"><div class="round"><span>REACTION RUSH</span><span>Wait for GREEN</span></div><div id="react" class="reaction">WAIT…</div></div>`}function initReaction(){const r=$('#react'),delay=1200+Math.random()*3500;r.onclick=()=>{if(!r.classList.contains('go'))return toast('Too early! 😈');const t=performance.now()-r.dataset.start;toast(Math.round(t)+' ms! ⚡');addScore(Math.max(10,300-Math.round(t/5)));r.className='reaction';r.textContent='WAIT…';initReaction()};setTimeout(()=>{r.className='reaction go';r.textContent='CLICK!';r.dataset.start=performance.now()},delay)}
function word(){return `<div class="fun"><div class="emoji">🔤</div><h3>Word Chain</h3><p>Type a word beginning with the last letter.</p><div class="answer" id="chain">START</div><input class="answer" id="wi" placeholder="Your word"><button class="neon" onclick="chain()">SEND WORD</button><p id="wr"></p></div>`}function chain(){const i=$('#wi'),v=i.value.trim();if(!v)return;const last=$('#chain').textContent.trim().slice(-1).toLowerCase();if(v[0].toLowerCase()!==last)$('#wr').textContent='❌ Start with '+last.toUpperCase();else{$('#chain').textContent=v.toUpperCase();$('#wr').textContent='🔥 Chain continues!';addScore(25)}i.value=''}

// Keep inline HTML buttons working in every browser.
Object.assign(window,{createRoom,joinRoom,toggleJoin,startGame,showRoom,goHome,copyCode,guess,clearDraw,eraser,move,resetTTT,newTruth,newWould,vote,checkE,qa,chain,renderGame});
